#ifndef F
#error Define F before including this file
#endif

F(GetBucketRef)
F(Insert)
F(Get)
F(BeginAccess)
F(BeginReadOp)
F(ReadPathToStash)
F(ReadBlockOnPathToStash)
F(ReadBlockToStashedBlock)
F(ReadBucketToStash)
F(GetBucketMetadata)
F(ReadBlockFromStash)
F(FinishAccess)
F(FinishOramOp)
F(WriteToSomeStashedBlock)
F(EvictPath_ExternalMemory)
F(EvictPath)
F(LateReshuffle)
F(CleanUpStash_ExternalMemory)
// F(CleanUpStash)
F(ForceIntoStash)
F(PurgeFromStash)
F(WriteBucket)
F(BlockEncryption)
F(Encrypt)
F(Decrypt)
F(OBST)
F(ORAMClient)
F(FileServer)
F(MemServer)

F(GetBucketRef_Cache)
F(GetBucketRef_SlowPath)
F(ORAMClientInterface)

F(B1)
F(B2)
F(B3)
F(B4)
F(B5)
F(B6)
F(B7)
F(B8)
F(B9)
F(B10)
F(T_STASH_SIZE)
F(T_INIT_STASH_SIZE_1)
F(T_INIT_STASH_SIZE_2)
F(T_FINAL_STASH_SIZE_1)
F(T_FINAL_STASH_SIZE_2)

#undef F