#!/bin/bash
source /startsgxenv.sh

# Algorithms:
# BUCKETSORT
# OQUICKSORT
# CABUCKETSORT
# BITONICSORT
# BUCKETSHUFFLE
# ORSHUFFLE
# CABUCKETSHUFFLE
# BITONICSHUFFLE
# DISTRIBUTIONOSORT
# BUCKETSORT DISTRIBUTIONOSORT BUCKETSHUFFLE BITONICSORT ORSHUFFLE KWAYBUTTERFLYOSORT KWAYBUTTERFLYOSHUFFLE BUCKETSORT BUCKETSHUFFLE
# KWAYBUTTERFLYOSORT DISTRIBUTIONOSORT BITONICSORT CABUCKETSORT KWAYBUTTERFLYOSHUFFLE ORSHUFFLE BITONICSHUFFLE CABUCKETSHUFFLE

# ALGOs=(KWAYBUTTERFLYOSORT DISTRIBUTIONOSORT BITONICSORT CABUCKETSORT KWAYBUTTERFLYOSHUFFLE ORSHUFFLE BITONICSHUFFLE CABUCKETSHUFFLE)
MIN_ELEMENT_SIZE=128
MAX_ELEMENT_SIZE=128
ALGOs=(DISTRIBUTIONOSORT)
# MIN_SIZE=5000000
# MAX_SIZE=5000000
# MIN_SIZE=524288
# MAX_SIZE=419430402
MIN_SIZE=100000000
MAX_SIZE=100000000
MIN_ENCLAVE_SIZE=128 #MB
MAX_ENCLAVE_SIZE=128
IO_ROUND=1
CORE_ID=5
DISK_IO=0

if [ $IO_ROUND = 0 ]
then
    IO_TAG=_MOCK_IO
fi

if [ $IO_ROUND -gt 1 ]
then
    IO_TAG=_${IO_ROUND}IO
fi

if [ $DISK_IO = 1 ]
then
    DISK_TAG=_DISK
fi

if [ $MAX_ENCLAVE_SIZE != 128 ]
then
    ENCLAVE_SIZE_TAG=_${MIN_ENCLAVE_SIZE}_${MAX_ENCLAVE_SIZE}
fi

for ALGO in ${ALGOs[@]}; do
FILENAME=${ALGO}_${MIN_ELEMENT_SIZE}_${MAX_ELEMENT_SIZE}_${MIN_SIZE}_${MAX_SIZE}${IO_TAG}${DISK_TAG}${ENCLAVE_SIZE_TAG}.out
rm -f $FILENAME
echo "output to"${FILENAME}
for (( encsize=$MIN_ENCLAVE_SIZE; encsize<=$MAX_ENCLAVE_SIZE; encsize*=2 ))
do
heapsizeB=$(( encsize * 999424 ))
hex_encsize=$(printf '%x\n' $heapsizeB)

sed -i "/.*<Heap.*/c\  <HeapMaxSize>0x"${hex_encsize}"</HeapMaxSize>" ./Enclave/Enclave.config.xml
# for s in $(seq $MIN_ELEMENT_SIZE $ELEMENT_SIZE_STEP $MAX_ELEMENT_SIZE)
for (( s=$MIN_ELEMENT_SIZE; s<=$MAX_ELEMENT_SIZE; s=s*6/5 ))
do
    make clean
    make SGX_MODE=HW SGX_PRERELEASE=1 ELEMENT_SIZE=$s ALGO=$ALGO MIN_SIZE=$MIN_SIZE MAX_SIZE=$MAX_SIZE IO_ROUND=$IO_ROUND DISK_IO=$DISK_IO ENCLAVE_SIZE=$encsize
    taskset -c ${CORE_ID} stdbuf -oL nohup ./signal.elf &>> $FILENAME < /dev/null
    sleep 1
done
done
done
sed -i '/.*<Heap.*/c\  <HeapMaxSize>0x7A00000</HeapMaxSize>' ./Enclave/Enclave.config.xml